#!/usr/bin/env python3
"""
Leaderboard Flask app.

Routes:
  GET  /                    → dashboard (filterable)
  GET  /api/leaderboard     → JSON list of all submissions
  POST /api/submit          → accept evaluation results
  GET  /api/submission/<id> → full detail for one submission
"""

import os, sys, json, sqlite3, math
from datetime import datetime, timezone
from flask import Flask, request, jsonify, render_template, g

HERE = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.path.join(HERE, "leaderboard.db")

# Path to fifo baselines file (generated by baselines.sh)
FIFO_BASELINES_FILE = os.path.join(os.path.dirname(HERE), "fifo_baselines.json")

TRACES = ["w86", "w87", "w89", "w90", "w93", "w94", "w99", "w103", "w105", "w106"]
SIZES  = ["1pct", "3pct", "10pct"]

app = Flask(__name__)


# ---------------------------------------------------------------------------
# DB helpers
# ---------------------------------------------------------------------------

def get_db():
    if "db" not in g:
        g.db = sqlite3.connect(DB_PATH, detect_types=sqlite3.PARSE_DECLTYPES)
        g.db.row_factory = sqlite3.Row
    return g.db


@app.teardown_appcontext
def close_db(_):
    db = g.pop("db", None)
    if db:
        db.close()


def init_db():
    db = sqlite3.connect(DB_PATH)
    db.execute("""
        CREATE TABLE IF NOT EXISTS submissions (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            submitter_name  TEXT NOT NULL,
            group_name      TEXT,
            heuristic_name  TEXT NOT NULL,
            description     TEXT,
            algo_type       TEXT DEFAULT 'vulcanevolve',
            submitted_at    TEXT NOT NULL,
            results_json    TEXT NOT NULL,
            mrr             REAL,
            mean_obj_hr     REAL,
            mean_byte_hr    REAL
        )
    """)
    db.commit()
    db.close()


# ---------------------------------------------------------------------------
# FIFO baselines (loaded once at startup)
# ---------------------------------------------------------------------------

FIFO_BASELINES: dict = {}

def load_fifo_baselines():
    global FIFO_BASELINES
    if os.path.exists(FIFO_BASELINES_FILE):
        with open(FIFO_BASELINES_FILE) as f:
            data = json.load(f)
        FIFO_BASELINES = data.get("results", {})
        print(f"[leaderboard] Loaded FIFO baselines for {len(FIFO_BASELINES)} scenarios")
    else:
        print(f"[leaderboard] WARNING: FIFO baselines not found at {FIFO_BASELINES_FILE}")
        print("[leaderboard]   Run baselines.sh first to generate them.")


# ---------------------------------------------------------------------------
# MRR computation (server-side)
# ---------------------------------------------------------------------------

def compute_mrr(results: dict, metric: str = "byte_hit_rate") -> float | None:
    """Mean ratio to FIFO across all scenario keys present in both dicts."""
    if not FIFO_BASELINES:
        return None
    ratios = []
    for key, data in results.items():
        fifo_val = FIFO_BASELINES.get(key, {}).get(metric, 0.0)
        if fifo_val > 0:
            ratios.append(data[metric] / fifo_val)
    return sum(ratios) / len(ratios) if ratios else None


def compute_summary_stats(results: dict) -> tuple[float, float]:
    obj_vals  = [v["obj_hit_rate"]  for v in results.values() if v.get("obj_hit_rate",  0) > 0]
    byte_vals = [v["byte_hit_rate"] for v in results.values() if v.get("byte_hit_rate", 0) > 0]
    mean_obj  = sum(obj_vals)  / len(obj_vals)  if obj_vals  else 0.0
    mean_byte = sum(byte_vals) / len(byte_vals) if byte_vals else 0.0
    return round(mean_obj, 6), round(mean_byte, 6)


# ---------------------------------------------------------------------------
# API routes
# ---------------------------------------------------------------------------

@app.post("/api/submit")
def api_submit():
    data = request.get_json(force=True)
    if not data:
        return jsonify({"error": "no JSON body"}), 400

    meta    = data.get("metadata", {})
    results = data.get("results",  {})

    for field in ("submitter_name", "heuristic_name"):
        if not meta.get(field):
            return jsonify({"error": f"missing metadata field: {field}"}), 422

    mrr            = compute_mrr(results)
    mean_obj, mean_byte = compute_summary_stats(results)
    submitted_at   = datetime.now(timezone.utc).isoformat()

    db = get_db()
    cur = db.execute(
        """INSERT INTO submissions
           (submitter_name, group_name, heuristic_name, description,
            algo_type, submitted_at, results_json, mrr, mean_obj_hr, mean_byte_hr)
           VALUES (?,?,?,?,?,?,?,?,?,?)""",
        (
            meta.get("submitter_name"),
            meta.get("group_name", ""),
            meta.get("heuristic_name"),
            meta.get("description", ""),
            meta.get("algo_type", "vulcanevolve"),
            submitted_at,
            json.dumps(results),
            mrr,
            mean_obj,
            mean_byte,
        ),
    )
    db.commit()
    return jsonify({
        "id":            cur.lastrowid,
        "submitted_at":  submitted_at,
        "mrr":           mrr,
        "mean_obj_hr":   mean_obj,
        "mean_byte_hr":  mean_byte,
    }), 201


@app.get("/api/leaderboard")
def api_leaderboard():
    """
    Query params:
      sort     = mrr | mean_byte_hr | mean_obj_hr          (default: mrr)
      trace    = w106 (filter to only scenarios for that trace)
      size     = 1pct | 3pct | 10pct
      metric   = byte_hit_rate | obj_hit_rate               (for per-cell sort)
      limit    = int (default 100)
    """
    sort_by  = request.args.get("sort", "mrr")
    trace_f  = request.args.get("trace")
    size_f   = request.args.get("size")
    limit    = min(int(request.args.get("limit", 100)), 500)

    valid_sorts = {"mrr", "mean_byte_hr", "mean_obj_hr", "submitted_at"}
    if sort_by not in valid_sorts:
        sort_by = "mrr"

    order_dir = "DESC" if sort_by != "submitted_at" else "DESC"
    rows = get_db().execute(
        f"SELECT * FROM submissions ORDER BY {sort_by} {order_dir} LIMIT ?", (limit,)
    ).fetchall()

    out = []
    for row in rows:
        results = json.loads(row["results_json"])

        # optional trace / size filter: compute filtered mean byte_hit_rate
        if trace_f or size_f:
            filtered = {
                k: v for k, v in results.items()
                if (not trace_f or k.startswith(trace_f))
                and (not size_f or k.endswith(size_f))
            }
            byte_vals = [v["byte_hit_rate"] for v in filtered.values() if v.get("byte_hit_rate", 0) > 0]
            obj_vals  = [v["obj_hit_rate"]  for v in filtered.values() if v.get("obj_hit_rate",  0) > 0]
            display_byte = sum(byte_vals)/len(byte_vals) if byte_vals else 0
            display_obj  = sum(obj_vals) /len(obj_vals)  if obj_vals  else 0
        else:
            display_byte = row["mean_byte_hr"]
            display_obj  = row["mean_obj_hr"]
            filtered     = results

        out.append({
            "id":             row["id"],
            "submitter_name": row["submitter_name"],
            "group_name":     row["group_name"],
            "heuristic_name": row["heuristic_name"],
            "description":    row["description"],
            "algo_type":      row["algo_type"],
            "submitted_at":   row["submitted_at"],
            "mrr":            row["mrr"],
            "mean_byte_hr":   display_byte,
            "mean_obj_hr":    display_obj,
            "scenario_results": filtered,
        })

    return jsonify(out)


@app.get("/api/submission/<int:sub_id>")
def api_submission_detail(sub_id: int):
    row = get_db().execute(
        "SELECT * FROM submissions WHERE id=?", (sub_id,)
    ).fetchone()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({
        **dict(row),
        "results": json.loads(row["results_json"]),
    })


@app.get("/api/fifo_baselines")
def api_fifo_baselines():
    return jsonify(FIFO_BASELINES)


# ---------------------------------------------------------------------------
# Dashboard
# ---------------------------------------------------------------------------

@app.get("/")
def dashboard():
    return render_template(
        "index.html",
        traces=TRACES,
        sizes=SIZES,
    )


# ---------------------------------------------------------------------------
# Start
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    init_db()
    load_fifo_baselines()
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port, debug=True)
